version: '3'
      
services:
  mysql_db:
    container_name: mysql-container
    image: mysql:latest
    restart: always      
    volumes:
      - mysql:/var/lib/mysql 

  wordpress:
    depends_on:
      - mysql_db
    container_name: wordpress-container
    image: wordpress:latest 
    restart: always   
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: mysql_db:3306
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: wordpress_user
    volumes:
      - "./:/var/www/html"  

  phpmyadmin:
    depends_on:  
      - mysql_db
    container_name: phpmyadmin-container
    image: phpmyadmin/phpmyadmin
    restart: always   
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql_db  
    volumes:
      - "./:/var/www/html/phpmyadmin" 
    
  volumes:
    mysql: {}
